from pwn import *
import time

context.log_level = 'debug'
# rr = process(['bash', './rr.sh'])
rr = remote('120.46.65.156', 32106)
rr.recvuntil(b'Submit the token generated by `')
import os
token = os.popen(rr.recvuntil(b'`')[:-1].decode()).read().split('hashcash token: ')[-1].strip()
rr.sendline(token.encode())
data = open('../solver-build/shim', 'rb').read()
rr.recvuntil(b'Please input your static executable file (in HEX, ends with empty line): ')
for i in range(0, len(data), 256):
    rr.sendline(data[i:i+256].hex().encode())
    time.sleep(0.1)
rr.sendline()
rr.interactive()