FROM php:8.0.22-apache

COPY ./craftcms-4.4.14-src-after-setup /var/www/html
COPY ./host.conf /etc/apache2/sites-available/000-default.conf
COPY ./flag /
COPY ./readflag /
COPY ./init.sql /tmp
COPY ./start.sh /start.sh

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free non-free-firmware" >/etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main contrib non-free non-free-firmware" >>/etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-backports main contrib non-free non-free-firmware" >>/etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev libzip-dev libicu-dev libonig-dev libxml2-dev curl unzip git libmagickwand-dev mariadb-server && \
    docker-php-ext-install -j$(nproc) iconv && \
    docker-php-ext-install -j$(nproc) mbstring && \
    docker-php-ext-install -j$(nproc) mysqli  && \
    docker-php-ext-install -j$(nproc) pdo_mysql && \
    docker-php-ext-install -j$(nproc) gd && \
    docker-php-ext-install -j$(nproc) intl && \
    docker-php-ext-install -j$(nproc) zip && \
    docker-php-ext-install -j$(nproc) bcmath && \
    docker-php-ext-install -j$(nproc) ctype && \
    docker-php-ext-install -j$(nproc) dom && \
    pecl install imagick && docker-php-ext-enable imagick && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    chmod 700 /flag && \
    chmod +sx /readflag && \
    chmod -R 777 /var/www/html/storage && \
    chmod -R 777 /var/www/html/config && \
    chmod -R 777 /var/www/html/web/cpresources && \
    a2enmod rewrite

RUN mysqld_safe & \
    sleep 10s && \
    mysql -u root -e "CREATE DATABASE craftcms;" && \
    mysql -u root -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'actf2023passW0rdforCraftcms';" && \
    mysql -u root -e "GRANT ALL PRIVILEGES ON craftcms.* TO 'admin'@'localhost';" && \
    mysql -u root -e "FLUSH PRIVILEGES;" && \
    mysql -u root craftcms < /tmp/init.sql

EXPOSE 80

CMD /bin/bash /start.sh && tail -f /etc/passwd